### ISSUE TITLE
replace icons with svgs

### ISSUE THREAD

**Issue by mascazubi** [cunybpl/nycet_pnp#228]
For users with high DPI displays or high zoom level either via browser or operating system, icons can look a bit blurry. These are currently png images.

![image](https://github.com/user-attachments/assets/acaf5ca2-65b9-4945-b426-f42ac389899f)

To ensure there is no blur, the pngs mus be replaced by svgs and color css rules added for normal and hover states.

## TODO

- [x]  create svgs
- [x]  make svgs inline code
- [x]  add inline svgs to landing page horizontal nav
- [x]  add inline svgs to guide content page nav 
- [x]  style svgs
